### ISSUE TITLE
The Fall-out-of-world protection doesn't work

### ISSUE THREAD

**Issue by ArcheCraft** [Cassunshine/Pads#1]
The check for the player's y position is only executed if the player would teleport this tick, but when your falling out of the world you are normally not standing on a telepad at the same time :)

To fix this, just swap lines [73 and 75 in PadsMod.java](https://github.com/Cassunshine/Pads/blob/1.19.3/src/main/java/com/cassunshine/pads/PadsMod.java#L73-L75).

**Comment by Cassunshine** [comment]
Fixed in latest commit (https://github.com/Cassunshine/Pads/commit/52e303b4f3c29f439356fa86d588b49babdeaac6), closing!
